version: "3.9"

services:
  web:
    container_name: url_shortener
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: runserver
    volumes:
      - ../:/code
    ports:
      - 8001:8001
    depends_on:
      - db
    environment:
      - SECRET_KEY=9999
      - DEBUG=True
    networks:
      - shortener

  db:
    image: postgres:15
    container_name: url_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=devel
      - POSTGRES_DB=shortener
    expose:
      - "5432"
    networks:
      - shortener

volumes:
  postgres_data:

networks:
  shortener:
    external: false
