# Generated by Django 4.2 on 2023-05-05 17:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("full_url", models.URLField()),
                ("short_url", models.URLField()),
                ("hits", models.BigIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
