# Generated by Django 4.2 on 2023-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="full_url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="short_url",
            field=models.URLField(unique=True),
        ),
    ]
